name: Deploy Pages

on:
  workflow_run:
    workflows: ["Generate Feeds"]
    types:
      - completed

permissions:
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages

    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v5
